name: Test

on:
    pull_request:
        paths:
            - "*"

    push:
        branches:
            - main
            - rollout

jobs:
    test:
        timeout-minutes: 2
        runs-on: ubuntu-latest
        steps:
            - name: Install deps
              run: |
                  npm install

            - name: Run basic test
              run: |
                  npm run test
