name: Test

on:
    push:
        branches:
            - main

jobs:
    test:
        timeout-minutes: 2
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install deps
              run: |
                  npm install

            - name: Run basic test
              run: |
                  npm run test
